### ISSUE TITLE
Set images in HTML

### ISSUE THREAD

**Issue by awps** [seyedi/Covering-Bad#1]
Hello.
First of all I want to say that this plugin is great. Why? Not because it is unique, but because it is lightweight. I never use jquery plugins that have a lot of options and a crazy source code, I like it to be simple and to do only what it need to do. That plugin is exactly so. 

Second. I don't like only one thing. We can't set the images directly in HTML, this is a big no, because if I will implement it in a CMS, the images will be generated dinamically and will be hard to create css for each post.
I think you understand me and here's how(in my oppinion) it will be the best solution:

``` html
<div class="covered" data-passive="image.jpg" data-active="image2.jpg">
    <div class="handle"></div>
    <div class="changeable"></div>
</div>
```

What do you think? ;)

**Comment by awps** [comment]
Hmm, looks like I've missed some parts of this plugin. I'm able to set image using inline CSS(adding `style` tag to `.covered` and `.changeable`). This somehow fix my problem. :)
Anyways, let me know if using `data-*` would be better or not. ;)

**Comment by seyedi** [comment]
Hi @Smartik89 
Thanks for your idea about using the data attributes. I added it to the plugin.
